### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by phier61**
Changed syntax for command line for:

https://github.com/jNizM/ahk_notepad-plus-plus/blob/master/README.md#if-autohotkey-v2-is-installed

I believe 'L' should be '1'

### CODE REVIEW

**Comment by white-gthb** [comment]
Why do you believe that? On old systems using %1 may give the short path (8.3 names), using %L always gives the long path.
When you use the Browse button to select a program (like for example Notepad++.exe) %L is also used.

(Specifying the path to Notepad++.exe is not necessary for recent versions of Notepad++ because the installer adds an entry for Notepad++ to the "App Paths" key in the Windows registry. )

**Comment by phier61** [comment]
So sorry, I was mistaken! I was conflating the syntax for Windows batch files (where %1 indicates the first argument) with shell open commands, so I made the assumption that this was a typo.   
  

  
I didn't even know about the shell open command line arguments, so you have educated me   through this process!
  

  
Sorry to have wasted your time, but thank you for the details which helped me to learn something new. I have closed the pull request and deleted my copy of the repository.
  

  
Finally, thank you for this awesome Notepad++ language file!   
  

  

  
  
  
  
  
>

**Comment by white-gthb** [comment]
I tried to find more info. I found the following text [here](https://www.pcreview.co.uk/threads/how-to-pass-short-filename-in-context-menu.424801/#post-1284353):

> %1 passes long file names to 32 bit programs and Win 95 aware 16 bit programs. It passes shortfile names to 16 bit non win95 aware programs AND also to programs it can't find.

If it's true then using %L for Notepad++ has no benefit over using %1. Notepad++ is not a 16-bit program non win95 aware program ;)

So I think %L can be replaced all 3 times in README.md.

**Comment by phier61** [comment]
Makes sense, but it also seems that it's fine to leave %L in there.
  

  
Thanks for the follow-up!   
  

  

  

  

  
  
  
  
  
>

**Pull request closed without merging**
